-- DEFLUID example
-- This example shows how can you modify defluid game object by sending messages to its script.

function init(self)
	msg.post("/defluid", "activate")	-- activate creation of metaballs (fluid)
	msg.post("/defluid", "change", {dry_each_after = 1})	-- change param of defluid
	msg.post("/defluid", "dry")			-- activate drying (dry a metaball every second)
end

function final(self)
	msg.post("/defluid", "remove")		-- if needed you can destroy metaballs anytime
end